background {
    monitor =
    path = ~/Images/Wallpaper/wallpaper-DP4.png
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(150, 150, 150)
    inner_color = rgb(20, 20, 20)
    font_color = rgb(200, 200, 200)
    placeholder_text = <i>Mot de passe...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 60
    position = 0, 100
    halign = center
    valign = center
}
