ipc = on
splash = false

wallpaper {
  monitor = DP-4
  path = /home/maxime/Images/Wallpaper/wallpaper2-dp4.png 
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/maxime/Images/Wallpaper/wallpaper2-dp4.png
  fit_mode = cover
}
