ipc = on
splash = false
preload = /home/maxime/wallpaper.jpgaper.jpg

wallpaper {
  monitor = DP-4
  path = /home/maxime/Images/Wallpaper/wallpaper-DP4.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/maxime/Images/Wallpaper/wallpaper-HDMI.png
  fit_mode = cover
}
